import { Community } from '../types';

export const COMMUNITIES: Community[] = [
  {
    id: 'windrose-pulte',
    name: 'Windrose',
    builder: 'Pulte Homes',
    city: 'Surprise',
    area: 'phoenix',
    priceFrom: 389990,
    priceTo: 520000,
    base: 'luke',
    distanceFromBase: 4.2,
    vaEligible: true,
    fhaEligible: true,
    seniorCommunity: false,
    amenities: ['Pool', 'Clubhouse', 'Park', 'Walking trails'],
    activeIncentives: ['Pulte Flex Cash 3%', 'Hometown Heroes $2K', '$15K QMI Bonus'],
    tags: ['VA Loan', 'BAH-eligible', 'Military Pick'],
    color: '#B5D4F4',
  },
  {
    id: 'marley-park-tm',
    name: 'Marley Park',
    builder: 'Taylor Morrison',
    city: 'Surprise',
    area: 'phoenix',
    priceFrom: 424990,
    priceTo: 580000,
    base: 'luke',
    distanceFromBase: 6.0,
    vaEligible: true,
    fhaEligible: true,
    seniorCommunity: false,
    amenities: ['Multiple pools', 'Park system', 'Splash pad', 'Events lawn'],
    activeIncentives: ['Builder rate buydown', 'Closing cost credit'],
    tags: ['VA Loan', 'Top-rated schools', 'Family-friendly'],
    color: '#9FE1CB',
  },
  {
    id: 'sterling-grove-tb',
    name: 'Sterling Grove',
    builder: 'Toll Brothers',
    city: 'Surprise',
    area: 'phoenix',
    priceFrom: 549000,
    priceTo: 850000,
    base: 'luke',
    distanceFromBase: 8.0,
    vaEligible: true,
    fhaEligible: false,
    seniorCommunity: false,
    amenities: ['Golf course', 'Luxury clubhouse', 'Resort pool', 'Fitness center'],
    activeIncentives: ['Design studio credit', 'Rate incentive'],
    tags: ['Golf community', 'Luxury', 'Gated'],
    color: '#CECBF6',
  },
  {
    id: 'sun-city-festival-dw',
    name: 'Sun City Festival',
    builder: 'Del Webb',
    city: 'Buckeye',
    area: 'phoenix',
    priceFrom: 319990,
    priceTo: 520000,
    base: null,
    distanceFromBase: null,
    vaEligible: true,
    fhaEligible: true,
    seniorCommunity: true,
    amenities: ['Fitness center', 'Pickleball', 'Indoor pool', 'Arts & crafts', 'Golf'],
    activeIncentives: ['$10-20K design credit', 'Hometown Heroes $2K', 'Accessibility upgrades included'],
    tags: ['55+ Active Adult', 'Low-maintenance', 'Lifestyle community'],
    color: '#FAC775',
  },
  {
    id: 'encanterra-shea',
    name: 'Encanterra',
    builder: 'Shea Homes',
    city: 'Queen Creek',
    area: 'phoenix',
    priceFrom: 349990,
    priceTo: 650000,
    base: null,
    distanceFromBase: null,
    vaEligible: true,
    fhaEligible: true,
    seniorCommunity: true,
    amenities: ['Resort pool', 'Pickleball', 'Tennis', 'Clubhouse', 'Restaurant'],
    activeIncentives: ['Design studio credit', 'Rate buydown'],
    tags: ['55+ Active Adult', 'Resort living', 'Popular'],
    color: '#F5C4B3',
  },
  {
    id: 'saguaro-trails-meritage',
    name: 'Saguaro Trails',
    builder: 'Meritage Homes',
    city: 'Tucson',
    area: 'tucson',
    priceFrom: 289990,
    priceTo: 390000,
    base: 'dm',
    distanceFromBase: 12.0,
    vaEligible: true,
    fhaEligible: true,
    seniorCommunity: false,
    amenities: ['Park', 'Walking trails', 'Playground'],
    activeIncentives: ['Pima DPA eligible', 'Energy Star savings', 'VA closing cost credit'],
    tags: ['Energy Star', 'FHA/VA', 'DPA eligible', 'FTB friendly'],
    color: '#FAC775',
  },
  {
    id: 'rancho-sahuarita',
    name: 'Rancho Sahuarita',
    builder: 'Multiple Builders',
    city: 'Sahuarita',
    area: 'tucson',
    priceFrom: 279990,
    priceTo: 420000,
    base: 'dm',
    distanceFromBase: 18.0,
    vaEligible: true,
    fhaEligible: true,
    seniorCommunity: false,
    amenities: ['Community lake', 'Pool', 'Park', 'Trails'],
    activeIncentives: ['Pima DPA eligible', 'FHA + DPA stack', 'VA incentives'],
    tags: ['First-time buyer', 'DPA eligible', 'Lakeside'],
    color: '#9FE1CB',
  },
  {
    id: 'vail-ranch-drhorton',
    name: 'Vail Ranch',
    builder: 'DR Horton',
    city: 'Vail',
    area: 'tucson',
    priceFrom: 259990,
    priceTo: 360000,
    base: 'dm',
    distanceFromBase: 22.0,
    vaEligible: true,
    fhaEligible: true,
    seniorCommunity: false,
    amenities: ['Park', 'Playground', 'Open space'],
    activeIncentives: ['VA closing cost credit', 'FHA rate incentive', '$5K flex cash'],
    tags: ['Affordable', 'VA Loan', 'FHA friendly'],
    color: '#B5D4F4',
  },
  {
    id: 'sierra-vista-richmond',
    name: 'Heritage Crossing',
    builder: 'Richmond American',
    city: 'Sierra Vista',
    area: 'tucson',
    priceFrom: 299990,
    priceTo: 430000,
    base: 'huachuca',
    distanceFromBase: 5.5,
    vaEligible: true,
    fhaEligible: true,
    seniorCommunity: false,
    amenities: ['Park', 'Trails', 'Playground'],
    activeIncentives: ['VA $0 down eligible', 'Rate buydown', 'Closing cost assist'],
    tags: ['Fort Huachuca', 'VA Loan', 'Military Pick'],
    color: '#D6E4F0',
  },
  {
    id: 'goodyear-meritage',
    name: 'Estrella',
    builder: 'Meritage Homes',
    city: 'Goodyear',
    area: 'phoenix',
    priceFrom: 359990,
    priceTo: 510000,
    base: 'luke',
    distanceFromBase: 14.0,
    vaEligible: true,
    fhaEligible: true,
    seniorCommunity: false,
    amenities: ['Lake', 'Multiple pools', 'Tennis', 'Golf nearby'],
    activeIncentives: ['Energy Star credit', 'VA incentive', 'DPA eligible'],
    tags: ['Lake community', 'Energy Star', 'VA Loan'],
    color: '#9FE1CB',
  },
  {
    id: 'prasada-drhorton',
    name: 'Prasada',
    builder: 'DR Horton',
    city: 'Surprise',
    area: 'phoenix',
    priceFrom: 329990,
    priceTo: 450000,
    base: 'luke',
    distanceFromBase: 6.5,
    vaEligible: true,
    fhaEligible: true,
    seniorCommunity: false,
    amenities: ['Pool', 'Park', 'Playground', 'Walking trails'],
    activeIncentives: ['VA $0 down', 'FHA rate incentive', '$5K closing cost credit'],
    tags: ['Affordable', 'VA Loan', 'FHA', 'Near Luke AFB'],
    color: '#B5D4F4',
  },
  {
    id: 'canyon-trails-meritage',
    name: 'Canyon Trails',
    builder: 'Meritage Homes',
    city: 'Goodyear',
    area: 'phoenix',
    priceFrom: 349990,
    priceTo: 490000,
    base: 'luke',
    distanceFromBase: 16.0,
    vaEligible: true,
    fhaEligible: true,
    seniorCommunity: false,
    amenities: ['Pool', 'Splash pad', 'Park', 'Sports courts'],
    activeIncentives: ['Energy Star savings', 'Rate buydown', 'VA eligible'],
    tags: ['Energy Star', 'Family-friendly', 'VA Loan'],
    color: '#9FE1CB',
  },
  {
    id: 'tartesso-drhorton',
    name: 'Tartesso',
    builder: 'DR Horton',
    city: 'Buckeye',
    area: 'phoenix',
    priceFrom: 289990,
    priceTo: 399990,
    base: null,
    distanceFromBase: null,
    vaEligible: true,
    fhaEligible: true,
    seniorCommunity: false,
    amenities: ['Pool', 'Park', 'Playground', 'Trails'],
    activeIncentives: ['$0 down VA', 'FHA + DPA stack', 'Quick move-in bonus'],
    tags: ['Affordable', 'First-time buyer', 'DPA eligible'],
    color: '#FAC775',
  },
  {
    id: 'verrado-tb',
    name: 'Verrado',
    builder: 'Toll Brothers',
    city: 'Buckeye',
    area: 'phoenix',
    priceFrom: 499990,
    priceTo: 750000,
    base: null,
    distanceFromBase: null,
    vaEligible: true,
    fhaEligible: false,
    seniorCommunity: false,
    amenities: ['Golf', 'Multiple pools', 'Town center', 'Fitness center', 'Walking trails'],
    activeIncentives: ['Design studio credit', 'Rate incentive', 'VA eligible'],
    tags: ['Master planned', 'Golf community', 'Luxury', 'VA Loan'],
    color: '#CECBF6',
  },
  {
    id: 'higley-heights-richmond',
    name: 'Higley Heights',
    builder: 'Richmond American',
    city: 'Gilbert',
    area: 'phoenix',
    priceFrom: 419990,
    priceTo: 580000,
    base: null,
    distanceFromBase: null,
    vaEligible: true,
    fhaEligible: true,
    seniorCommunity: false,
    amenities: ['Pool', 'Park', 'Playground'],
    activeIncentives: ['VA closing cost credit', 'Rate buydown', 'FHA incentive'],
    tags: ['Top schools', 'Family-friendly', 'VA Loan', 'Gilbert'],
    color: '#B5D4F4',
  },
  {
    id: 'layton-lakes-tm',
    name: 'Layton Lakes',
    builder: 'Taylor Morrison',
    city: 'Chandler',
    area: 'phoenix',
    priceFrom: 459990,
    priceTo: 650000,
    base: null,
    distanceFromBase: null,
    vaEligible: true,
    fhaEligible: true,
    seniorCommunity: false,
    amenities: ['Lake', 'Pool', 'Clubhouse', 'Walking trails', 'Park'],
    activeIncentives: ['Builder rate buydown', 'Closing cost credit', 'VA eligible'],
    tags: ['Lakeside', 'Top-rated schools', 'VA Loan', 'Chandler'],
    color: '#9FE1CB',
  },
  {
    id: 'adora-trails-drhorton',
    name: 'Adora Trails',
    builder: 'DR Horton',
    city: 'Gilbert',
    area: 'phoenix',
    priceFrom: 379990,
    priceTo: 510000,
    base: null,
    distanceFromBase: null,
    vaEligible: true,
    fhaEligible: true,
    seniorCommunity: false,
    amenities: ['Pool', 'Splash pad', 'Park', 'Trails', 'Clubhouse'],
    activeIncentives: ['VA $0 down', '$5K flex cash', 'FHA rate incentive'],
    tags: ['Family-friendly', 'VA Loan', 'Great schools', 'Gilbert'],
    color: '#F5C4B3',
  },
  {
    id: 'trilogy-at-vistancia-shea',
    name: 'Trilogy at Vistancia',
    builder: 'Shea Homes',
    city: 'Peoria',
    area: 'phoenix',
    priceFrom: 389990,
    priceTo: 620000,
    base: 'luke',
    distanceFromBase: 18.0,
    vaEligible: true,
    fhaEligible: true,
    seniorCommunity: true,
    amenities: ['Resort pool', 'Golf', 'Fitness center', 'Spa', 'Restaurant', 'Pickleball'],
    activeIncentives: ['Design studio credit $15K', 'Hometown Heroes $2K', 'VA eligible'],
    tags: ['55+ Active Adult', 'Golf community', 'Resort living', 'Near Luke AFB'],
    color: '#FAC775',
  },
  {
    id: 'sun-city-grand-dw',
    name: 'Sun City Grand',
    builder: 'Del Webb',
    city: 'Surprise',
    area: 'phoenix',
    priceFrom: 359990,
    priceTo: 560000,
    base: 'luke',
    distanceFromBase: 5.0,
    vaEligible: true,
    fhaEligible: true,
    seniorCommunity: true,
    amenities: ['4 Fitness centers', 'Indoor & outdoor pools', 'Golf', 'Pickleball', 'Arts & crafts'],
    activeIncentives: ['$10-20K design credit', 'Hometown Heroes $2K', 'VA $0 down eligible'],
    tags: ['55+ Active Adult', 'Near Luke AFB', 'Veteran friendly', 'Del Webb'],
    color: '#D6E4F0',
  },
  {
    id: 'marana-community-pulte',
    name: 'Gladden Farms',
    builder: 'Pulte Homes',
    city: 'Marana',
    area: 'tucson',
    priceFrom: 319990,
    priceTo: 460000,
    base: 'dm',
    distanceFromBase: 20.0,
    vaEligible: true,
    fhaEligible: true,
    seniorCommunity: false,
    amenities: ['Pool', 'Park', 'Playground', 'Walking trails'],
    activeIncentives: ['Pulte Flex Cash 3%', 'VA eligible', 'DPA eligible'],
    tags: ['VA Loan', 'DPA eligible', 'Marana', 'Near Davis-Monthan'],
    color: '#B5D4F4',
  },
  {
    id: 'civano-meritage',
    name: 'Civano',
    builder: 'Meritage Homes',
    city: 'Tucson',
    area: 'tucson',
    priceFrom: 299990,
    priceTo: 420000,
    base: 'dm',
    distanceFromBase: 8.0,
    vaEligible: true,
    fhaEligible: true,
    seniorCommunity: false,
    amenities: ['Community center', 'Pool', 'Park', 'Walking trails', 'Playground'],
    activeIncentives: ['Energy Star savings', 'VA closing cost credit', 'Pima DPA eligible'],
    tags: ['Energy Star', 'Near Davis-Monthan', 'DPA eligible', 'VA Loan'],
    color: '#9FE1CB',
  },
];
