import { Incentive } from '../types';

export const INCENTIVES: Incentive[] = [
  {
    id: 'va-zero-down',
    name: 'VA Zero Down Payment',
    category: 'va_loan',
    value: '$0 Down',
    valueNumeric: null,
    description: 'Full entitlement = no down payment required. No loan limits in 2026.',
    eligibility: ['veteran'],
    expiration: null,
    stackable: true,
    source: 'VA / Federal',
  },
  {
    id: 'va-no-pmi',
    name: 'No PMI — Ever',
    category: 'va_loan',
    value: '$145–$290/mo saved',
    valueNumeric: 200,
    description: 'VA loans never require private mortgage insurance regardless of down payment.',
    eligibility: ['veteran'],
    expiration: null,
    stackable: true,
    source: 'VA / Federal',
  },
  {
    id: 'disability-fee-waiver',
    name: 'Disability Funding Fee Waiver',
    category: 'va_loan',
    value: 'Up to $10,750+',
    valueNumeric: 8600,
    description: '10%+ service-connected disability = $0 VA funding fee. Must reflect on COE at closing.',
    eligibility: ['veteran'],
    expiration: null,
    stackable: true,
    source: 'VA / Federal',
  },
  {
    id: 'az-property-tax-exemption',
    name: 'AZ Property Tax Exemption',
    category: 'state_benefit',
    value: '$100–$200/mo',
    valueNumeric: 150,
    description: '100% P&T disabled veterans: zero property taxes in AZ with income qualification.',
    eligibility: ['veteran'],
    expiration: null,
    stackable: true,
    source: 'State of Arizona',
  },
  {
    id: 'az-home-plus-dpa',
    name: 'Arizona Home Plus DPA',
    category: 'state_program',
    value: '3–5% of loan',
    valueNumeric: null,
    description: 'Down payment assistance forgivable after 3 years. No first-time buyer requirement. FHA & VA eligible.',
    eligibility: ['veteran', 'first_time', 'relocation', 'senior'],
    expiration: null,
    stackable: true,
    source: 'Arizona Housing Finance Authority',
  },
  {
    id: 'pima-tucson-dpa',
    name: 'Pima/Tucson DPA',
    category: 'local_program',
    value: '4% of loan',
    valueNumeric: null,
    description: 'Pima County + City of Tucson. No first-time buyer requirement. Stackable with VA and FHA.',
    eligibility: ['veteran', 'first_time', 'relocation', 'senior'],
    expiration: null,
    stackable: true,
    source: 'Pima County / City of Tucson',
    areasApplicable: ['tucson'],
  },
  {
    id: 'pulte-flex-cash',
    name: 'Pulte Flex Cash',
    category: 'builder_incentive',
    value: '3% of base price',
    valueNumeric: null,
    description: 'Applied to price reduction, lot premiums, closing costs, or rate buydown. Select Arizona communities.',
    eligibility: ['veteran', 'first_time', 'relocation', 'senior'],
    expiration: '2026-05-31',
    stackable: true,
    source: 'Pulte Homes',
    builderSpecific: 'pulte',
  },
  {
    id: 'hometown-heroes',
    name: 'Hometown Heroes Credit',
    category: 'builder_incentive',
    value: '$2,000',
    valueNumeric: 2000,
    description: 'Active and retired military + veterans. Available at Pulte and Del Webb communities.',
    eligibility: ['veteran'],
    expiration: null,
    stackable: true,
    source: 'Pulte / Del Webb',
  },
  {
    id: 'builder-rate-buydown',
    name: 'Builder 2/1 Rate Buydown',
    category: 'builder_incentive',
    value: '~$400+/mo in Year 1',
    valueNumeric: 400,
    description: 'Multiple builders offering temporary 2/1 buydowns. Year 1 rates as low as 4.875% on quick move-ins.',
    eligibility: ['veteran', 'first_time', 'relocation', 'senior'],
    expiration: null,
    stackable: true,
    source: 'Multiple Builders',
  },
  {
    id: 'senior-design-credit',
    name: '55+ Design Studio Credit',
    category: 'builder_incentive',
    value: '$10,000–$20,000',
    valueNumeric: 15000,
    description: 'Del Webb and Shea Homes offer design studio credits for active adult buyers. Includes accessibility upgrades.',
    eligibility: ['senior'],
    expiration: null,
    stackable: true,
    source: 'Del Webb / Shea Homes',
  },
  {
    id: 'va-one-time-close',
    name: 'VA One-Time Close Construction Loan',
    category: 'va_loan',
    value: '$3,000–$5,000 saved',
    valueNumeric: 4000,
    description: 'Single closing for land + construction + permanent loan. Eliminates duplicate closing costs.',
    eligibility: ['veteran'],
    expiration: null,
    stackable: true,
    source: 'VA / Lenders',
  },
];
