import { BuyerType, JourneyStageDefinition } from '../types';

export const VETERAN_JOURNEY: JourneyStageDefinition[] = [
  {
    number: 1,
    name: 'Pre-Approval',
    description: 'Get your VA Certificate of Eligibility and VA loan pre-approval',
    icon: 'shield-checkmark-outline',
    estimatedDays: 14,
    agentTip: "Your BAH is your buying power. Let's calculate exactly what your monthly benefit supports in today's market.",
    documentsNeeded: ['DD-214 or Statement of Service', 'Last 2 years W-2s', 'Last 30 days pay stubs', 'Bank statements (2 months)'],
    tasks: [
      {
        text: 'Order VA Certificate of Eligibility (COE)',
        detail: 'Your COE proves to lenders that you qualify for a VA loan. You can request it online through the VA eBenefits portal or your lender can pull it directly.',
        why: 'Without a COE, lenders cannot process your VA loan application.',
        how: 'Visit VA.gov/housing-assistance or have your lender submit VA Form 26-1880.',
        agentNote: 'Most lenders can pull your COE instantly using the VA\'s automated system. Takes about 5 minutes.',
      },
      {
        text: 'Contact a VA-approved lender',
        detail: 'Not all lenders work with VA loans. A VA-approved lender specializes in VA loan processing and understands VA appraisals for new construction.',
        why: 'Using an inexperienced lender can cause delays or denials on new construction timelines.',
        how: "I'll connect you with VA-approved lenders who have experience with Arizona new construction.",
        agentNote: 'New construction VA loans require a lender who understands the builder\'s closing timeline — usually 6-12 months.',
      },
      {
        text: 'Check disability rating for funding fee waiver',
        detail: 'Veterans with a 10% or higher service-connected disability rating are exempt from the VA funding fee, which can save $5,000–$15,000+.',
        why: 'This is free money — the funding fee is typically 2.15-3.3% of the loan amount.',
        how: 'Check your VA disability rating on VA.gov/disability. Your COE will reflect the exemption.',
        agentNote: "If you have a pending rating, don't wait — close the loan with the exemption if your rating is already approved.",
      },
      {
        text: 'Calculate BAH buying power',
        detail: 'Your Basic Allowance for Housing can be counted as qualifying income for your VA loan, significantly increasing what you can afford.',
        why: "BAH can add $1,600–$3,600/month to your qualifying income, which translates to $80K–$180K more home.",
        how: "I'll pull your exact BAH rate by base, grade, and dependent status and run the numbers.",
        agentNote: 'BAH is not taxed, but it IS counted as income by VA lenders. This is a huge advantage over civilian buyers.',
      },
    ],
  },
  {
    number: 2,
    name: 'Community Search',
    description: 'Find your perfect new construction community near your base',
    icon: 'search-outline',
    estimatedDays: 21,
    agentTip: "I've pre-filtered communities by VA loan eligibility and base commute. Let's schedule tours this weekend.",
    tasks: [
      {
        text: 'Research communities within base commute',
        detail: 'Communities near Luke AFB in the West Valley, or near Davis-Monthan/Fort Huachuca in the Tucson area that fit your commute requirements.',
        why: 'A long commute on top of a mortgage is stressful. Balancing location and budget is key.',
        how: "Use the Communities tab to filter by your base — I've pre-calculated distances.",
        agentNote: 'Most active duty members prefer under 30 minutes to gate. I know exactly which communities hit that mark.',
      },
      {
        text: 'Check VA loan eligibility per community',
        detail: 'Most new construction communities accept VA loans, but a few luxury or 55+ communities have restrictions.',
        why: 'Confirming VA eligibility upfront saves you from falling in love with a community you cannot finance.',
        how: "All communities in the app are tagged with VA eligibility. Green checkmark = VA approved.",
        agentNote: 'I verify VA eligibility with every builder before adding them to your list.',
      },
      {
        text: 'Review active incentives and expiration dates',
        detail: 'Builder incentives often have hard expiration dates. Missing a Flex Cash deadline can cost you $12,000–$15,000.',
        why: 'Timing your purchase to align with incentive windows maximizes your savings.',
        how: "Check the Incentives tab — I've flagged everything expiring within 60 days.",
        agentNote: "Pulte's Flex Cash is the big one right now — it ends May 31. We need to move if that's your target.",
      },
      {
        text: 'Schedule model home tours',
        detail: "Walking a model home gives you a real feel for the community, builder quality, and what's included vs. upgraded.",
        why: "You're buying from a model — the model shows premium upgrades that aren't included in the base price.",
        how: "I'll go with you to every tour. Never go to a builder sales office without your agent — you can't add me later.",
        agentNote: 'Critical: register me as your agent on your very first visit to the sales office or the builder may refuse to pay my commission.',
      },
    ],
  },
  {
    number: 3,
    name: 'Lot & Home Selection',
    description: 'Reserve your lot and select your floor plan',
    icon: 'home-outline',
    estimatedDays: 14,
    agentTip: 'Corner lots and cul-de-sac lots hold value better. Premium lots are worth considering if your BAH supports it.',
    tasks: [
      {
        text: 'Choose your floor plan',
        detail: "New construction builders offer 3-8 floor plan options. Consider your lifestyle, number of bedrooms needed, single vs. two-story (accessibility), and resale value.",
        why: "You're locked into your floor plan once you sign — choose wisely.",
        how: "I'll walk you through each plan with a resale and lifestyle analysis.",
        agentNote: "Single-story plans are in highest demand and command a premium on resale — worth considering even if you don't need it now.",
      },
      {
        text: 'Select and reserve your lot',
        detail: 'Lot location affects your view, privacy, noise level, and resale value. Premium lots (corner, cul-de-sac, larger, view) cost extra but appreciate better.',
        why: 'Your lot is the one thing you cannot change. Spend time here.',
        how: "I'll do a lot analysis comparing premium vs. standard lots in your selected community.",
        agentNote: 'Builders sometimes negotiate lot premiums when they need to move inventory. I know which ones are flexible.',
      },
      {
        text: 'Review quick move-in vs. build timeline',
        detail: "Quick move-in homes (QMI) are already under construction or complete. They close faster (30-90 days) but have less customization. Build-to-order takes 6-12 months.",
        why: "Your closing timeline affects your orders, housing during build, and rate lock strategy.",
        how: "We'll map out your PCS orders (if applicable) against available QMI and build timelines.",
        agentNote: 'If you have PCS orders with a specific report date, QMIs are your best friend.',
      },
      {
        text: 'Understand lot reservation and earnest money',
        detail: "Most builders require a lot reservation fee ($500-$5,000) to hold your lot, then earnest money ($5,000-$20,000) at contract. These amounts vary by builder.",
        why: 'Understanding what you\'re committing before you sign protects you.',
        how: "I'll review the reservation terms with you before you write any checks.",
        agentNote: 'Earnest money is at risk if you cancel outside the builder\'s allowed windows — understand those terms.',
      },
    ],
  },
  {
    number: 4,
    name: 'Contract & Design',
    description: 'Sign your purchase agreement and personalize your home',
    icon: 'document-text-outline',
    estimatedDays: 30,
    agentTip: "The design center is exciting but dangerous — upgrades add up fast. I'll help you pick what adds value vs. what to do yourself after closing.",
    documentsNeeded: ['Pre-approval letter', 'COE (for VA loan)', 'Government ID'],
    tasks: [
      {
        text: 'Review purchase agreement with your agent',
        detail: "Builder contracts are long, builder-favorable, and non-standard. They are NOT like resale contracts. Key items: contingencies, cancellation terms, price escalation clauses.",
        why: "You're signing a legally binding agreement. One missed clause can cost you thousands.",
        how: "I review every builder contract line by line before you sign anything.",
        agentNote: "Builders rarely negotiate price, but they DO negotiate on incentives, lot premiums, closing costs, and upgrade allowances.",
      },
      {
        text: 'Design center appointment',
        detail: "The design center is where you select flooring, cabinets, counters, fixtures, and upgrades. Sessions can last 4-8 hours.",
        why: "Your upgrade choices affect your appraisal, livability, and resale — but overspending on upgrades rarely returns full value.",
        how: "I'll give you a pre-design-center briefing on what to upgrade (flooring, counters) vs. skip (things you can DIY).",
        agentNote: "Hard surfaces — tile and hardwood — return value. Carpet and basic fixtures do not. Focus upgrade budget there.",
      },
      {
        text: 'Select upgrades wisely',
        detail: "Most builders offer 3 tiers of upgrades. Base items are builder-grade. Mid-tier adds value. Top-tier rarely returns value at resale.",
        why: "Every dollar you spend at the design center is added to your loan balance.",
        how: "I'll walk you through which upgrades appraisers consider in valuation.",
        agentNote: "Pre-wire for solar and smart home tech — cheap now, expensive to retrofit later.",
      },
      {
        text: 'Understand earnest money terms',
        detail: "Builder earnest money schedules differ from resale. Know when it becomes non-refundable and what triggers protect you.",
        why: "If you need to cancel for a VA-specific reason (failed appraisal, etc.), VA loan contingencies should protect you.",
        how: "Your purchase agreement will specify the earnest money schedule — I'll flag the key dates.",
        agentNote: "VA loans have specific protections built in. Make sure your purchase agreement includes the VA escape clause.",
      },
    ],
  },
  {
    number: 5,
    name: 'Construction Phase',
    description: 'Watch your home come to life — milestone by milestone',
    icon: 'construct-outline',
    estimatedDays: 180,
    agentTip: "Take photos at every stage. Pre-drywall inspection is your best opportunity to catch framing or wiring issues before they're covered.",
    tasks: [
      {
        text: 'Schedule pre-drywall inspection',
        detail: "A pre-drywall (frame) inspection happens before the drywall goes up. An independent inspector checks framing, electrical, plumbing, and insulation.",
        why: "Issues caught before drywall cost hundreds to fix. After drywall, they cost thousands.",
        how: "Hire an independent inspector — NOT the builder's inspector. I have trusted inspectors I work with.",
        agentNote: "Never skip this inspection. Builders are generally good, but nobody is perfect. This is your protection.",
      },
      {
        text: 'Track construction milestones',
        detail: "Builders typically provide milestone updates: foundation pour, framing, rough-ins, drywall, trim, final. Some provide photo updates.",
        why: "Staying engaged keeps you informed and allows you to address issues quickly.",
        how: "Most builders have a customer portal. I'll help you access it and interpret the updates.",
        agentNote: "I do periodic site visits and will alert you to anything I notice during construction.",
      },
      {
        text: 'Monitor VA appraisal timeline',
        detail: "VA appraisals on new construction are ordered at a specific stage. VA appraisers check construction progress against the plans.",
        why: "VA appraisals can cause closing delays if ordered too early or too late.",
        how: "I'll coordinate with your lender and builder on the VA appraisal timing.",
        agentNote: "VA appraisals have a Notice of Value (NOV) — if the home doesn't appraise at purchase price, you have options.",
      },
      {
        text: 'Schedule final walkthrough',
        detail: "The final walkthrough (blue tape walkthrough) is your opportunity to identify defects before closing. Make a list of everything that needs repair.",
        why: "Items on the blue tape list are the builder's contractual obligation to fix before or shortly after closing.",
        how: "I'll do the walkthrough with you and ensure the blue tape list is thorough.",
        agentNote: "Bring a flashlight, plug in a phone charger to test every outlet, and run every faucet.",
      },
    ],
  },
  {
    number: 6,
    name: 'Closing Prep',
    description: 'Final steps before your big day',
    icon: 'checkmark-circle-outline',
    estimatedDays: 30,
    agentTip: "Wire fraud is real — never wire money based on email instructions without calling your title company directly to verify the exact account.",
    documentsNeeded: ['Closing disclosure', 'Homeowner\'s insurance binder', 'Government ID', 'Certified funds or wire transfer confirmation'],
    tasks: [
      {
        text: 'Final loan approval (clear to close)',
        detail: "Your lender issues a 'Clear to Close' (CTC) when all conditions are satisfied. This is the green light for scheduling your closing date.",
        why: "No CTC = no closing. Know your lender's timeline so there are no last-minute surprises.",
        how: "Stay in weekly contact with your loan officer. Respond to document requests within 24 hours.",
        agentNote: "Don't make any large purchases, open credit cards, or change jobs between contract and closing — it can kill your loan.",
      },
      {
        text: 'Secure homeowner\'s insurance',
        detail: "Lenders require proof of insurance before closing. New construction requires a builder's risk or homeowner's policy effective on or before closing day.",
        why: "No insurance proof = no closing. Get quotes and bind coverage 2 weeks before closing.",
        how: "Shop multiple carriers — new construction rates vary widely. USAA and military-specific carriers often have great rates for veterans.",
        agentNote: "Get replacement cost coverage — not market value. These are different and market value coverage can leave you short.",
      },
      {
        text: 'Review Closing Disclosure (CD)',
        detail: "The CD shows your final loan terms, closing costs, and cash needed at closing. By law, you receive it at least 3 business days before closing.",
        why: "The CD should closely match your Loan Estimate. Any large discrepancies need to be questioned.",
        how: "I'll review the CD with you line by line. Compare it to your Loan Estimate for any surprises.",
        agentNote: "Watch for junk fees that weren't in your LE. Lenders sometimes slip in last-minute charges.",
      },
      {
        text: 'Confirm wire transfer instructions with title',
        detail: "The title company will send wire instructions for your closing funds. Call them directly (using a number from their website) to verify BEFORE wiring.",
        why: "Wire fraud targeting home buyers costs victims an average of $100,000+. Verification is non-negotiable.",
        how: "Call title company directly. Never wire based on email instructions alone.",
        agentNote: "I will remind you of this again closer to closing. This is the most important warning I can give you.",
      },
    ],
  },
  {
    number: 7,
    name: 'Close & Get Keys',
    description: "It's closing day — you made it!",
    icon: 'key-outline',
    estimatedDays: 1,
    agentTip: "Bring your ID, be ready to sign a lot of documents, and get ready to be a homeowner. This is your moment!",
    tasks: [
      {
        text: 'Wire closing funds',
        detail: "Wire your down payment and closing costs (if any) per the verified wire instructions from your title company. For VA loans with $0 down, you may only owe pre-paids and escrows.",
        why: "Funds must be received by the title company before closing can proceed.",
        how: "Initiate your wire the business day before closing. Confirm receipt the morning of closing.",
        agentNote: "VA loans often require zero or minimal cash to close — your Flex Cash and lender credits may cover everything.",
      },
      {
        text: 'Sign closing documents',
        detail: "Closing can take 60-90 minutes. You'll sign 50+ documents covering the purchase, loan, title, and disclosures.",
        why: "Every document you sign is legally binding. Take your time and ask questions.",
        how: "I'll be at your closing table. Read what you sign — especially the loan note and deed of trust.",
        agentNote: "Bring snacks and water. Closings can run long, especially for VA loans which have additional forms.",
      },
      {
        text: 'Receive your keys',
        detail: "Once all documents are signed and funds are confirmed, the title company records the deed and you receive your keys!",
        why: "This is the moment. You own your home.",
        how: "Keys are typically handed over after recording confirmation, which can happen same day or next day.",
        agentNote: "I'll be there to celebrate with you. This moment is what all the hard work was for.",
      },
      {
        text: 'Change the locks',
        detail: "Builder superintendents, subcontractors, and sales staff all have keys to your home. Change the locks on all entry points on day one.",
        why: "You have no way of knowing how many keys are floating around.",
        how: "Get a locksmith within the first 24 hours, or rekey yourself if you're handy.",
        agentNote: "Also set up your security system and garage code immediately.",
      },
    ],
  },
];

export const FIRST_TIME_JOURNEY: JourneyStageDefinition[] = [
  {
    number: 1,
    name: 'Financial Readiness',
    description: 'Get your financial foundation solid before you shop',
    icon: 'cash-outline',
    estimatedDays: 30,
    agentTip: "Most first-time buyers think they need 20% down. With FHA and DPA programs, you may need as little as 0-3.5%.",
    tasks: [
      {
        text: 'Check your credit score',
        detail: "FHA loans require a minimum 580 credit score (3.5% down) or 500-579 (10% down). Conventional requires 620+. Higher scores = better rates.",
        why: "Your credit score determines your interest rate and which loan programs you qualify for.",
        how: "Check at AnnualCreditReport.com for free. Use Credit Karma to monitor. Dispute any errors immediately.",
        agentNote: "A 640 vs 700 credit score can mean 0.5-1% difference in rate on a $400K loan — that's $100-200/month.",
      },
      {
        text: 'Calculate your savings and DTI ratio',
        detail: "Debt-to-Income (DTI) ratio is your monthly debts divided by gross income. FHA allows up to 57% DTI with compensating factors. Conventional is typically 45-50%.",
        why: "DTI determines how much home you can qualify for.",
        how: "Add up all monthly debt payments (car, student loans, credit cards) and divide by gross monthly income.",
        agentNote: "Paying down a car loan or credit card before applying can dramatically improve your DTI and buying power.",
      },
      {
        text: 'Research down payment assistance programs',
        detail: "Arizona Home Plus DPA offers 3-5% of the loan amount as forgivable assistance. No repayment if you stay 3 years. Available on FHA and VA loans.",
        why: "DPA programs can eliminate or dramatically reduce your down payment requirement.",
        how: "I'll walk you through the AZ Home Plus program and whether you qualify based on income and area.",
        agentNote: "Many buyers don't know about DPA programs — this is one of the biggest advantages of working with an experienced agent.",
      },
      {
        text: 'Set your realistic budget',
        detail: "Your budget isn't just the purchase price — it includes property taxes, HOA fees, insurance, and maintenance. New construction is often more efficient on utilities.",
        why: "Buying at the top of your budget leaves no room for life's surprises.",
        how: "I'll build a full monthly cost estimate for any home you're considering, not just the mortgage payment.",
        agentNote: "New construction often has lower utility costs due to energy efficiency — factor that into your budget comparison vs. resale.",
      },
    ],
  },
  {
    number: 2,
    name: 'Program Selection',
    description: 'Choose the right loan program for your situation',
    icon: 'ribbon-outline',
    estimatedDays: 7,
    agentTip: "FHA + DPA is often the magic combo for first-time buyers. Let me run the numbers for your specific situation.",
    tasks: [
      {
        text: 'Compare FHA vs. Conventional loans',
        detail: "FHA: 3.5% down (with 580+ credit), more flexible DTI, includes MIP. Conventional: 3-5% down (with 620+ credit), PMI until 20% equity, better rates with higher credit.",
        why: "The right loan type saves you thousands over the life of the loan.",
        how: "Your lender will run both scenarios. Ask for side-by-side comparison of total monthly payment and 5-year cost.",
        agentNote: "For most first-time buyers with moderate credit, FHA + DPA beats conventional because the DPA covers the down payment gap.",
      },
      {
        text: 'Apply for Arizona Home Plus DPA',
        detail: "This state program provides 3-5% of the loan amount as a second mortgage that is forgivable after 3 years of living in the home.",
        why: "This can eliminate your down payment requirement entirely on homes under the program limit.",
        how: "Your DPA-approved lender applies for this simultaneously with your first mortgage. Ask specifically for AZ Home Plus.",
        agentNote: "Not all lenders do DPA. I work with lenders who specialize in first-time buyer programs in Arizona.",
      },
      {
        text: 'Get rate quotes from 3 lenders',
        detail: "Mortgage rates vary by lender. Shopping 3 lenders within a 14-day window counts as 1 credit inquiry. Even 0.25% difference saves thousands.",
        why: "The first lender you talk to isn't always the best. Competition gets you better terms.",
        how: "I'll give you a list of 3 recommended lenders who specialize in new construction FHA/DPA loans.",
        agentNote: "The builder's preferred lender may have extra incentives (closing cost credits) — always compare their offer too.",
      },
    ],
  },
  {
    number: 3,
    name: 'Pre-Approval',
    description: 'Get your pre-approval letter — your house hunting passport',
    icon: 'document-outline',
    estimatedDays: 7,
    agentTip: "A pre-approval letter is not the same as pre-qualification. Builders require full pre-approval with income verification.",
    documentsNeeded: ['Last 2 years W-2s or tax returns', 'Last 30 days pay stubs', '2 months bank statements', 'Government ID', 'Social Security Number'],
    tasks: [
      {
        text: 'Gather required documents',
        detail: "Lenders require income verification (W-2s, pay stubs), asset statements (bank accounts), and identification. Self-employed buyers need 2 years tax returns.",
        why: "Missing documents slow down your approval. Have everything ready before you apply.",
        how: "Create a folder (physical or digital) with all required documents before starting the application.",
        agentNote: "Organize your docs by category — income, assets, identity. This makes the process much smoother.",
      },
      {
        text: 'Submit your loan application',
        detail: "A full mortgage application (Uniform Residential Loan Application, Form 1003) collects all information the lender needs to issue a pre-approval.",
        why: "A full application results in a credit pull and income verification, making your pre-approval letter much stronger.",
        how: "Apply online or in-person with your chosen lender. The process takes about 30-45 minutes.",
        agentNote: "Apply with your top 2 lenders within the same week to minimize credit score impact while maximizing your options.",
      },
      {
        text: 'Receive and review pre-approval letter',
        detail: "Your pre-approval letter states the maximum loan amount and program you qualify for. Review it for accuracy before using it with builders.",
        why: "Errors in the pre-approval letter can cause issues later in the process.",
        how: "Check your name, loan amount, program type, and expiration date. Pre-approval letters are typically valid 60-90 days.",
        agentNote: "Never share your pre-approval letter's maximum amount with the builder's sales rep — they don't need to know your ceiling.",
      },
    ],
  },
  {
    number: 4,
    name: 'Community Search',
    description: 'Find your perfect new construction community',
    icon: 'search-outline',
    estimatedDays: 21,
    agentTip: "New construction offers a warranty, modern energy efficiency, and no deferred maintenance. It's a great first home choice.",
    tasks: [
      {
        text: 'Match communities to budget and lifestyle',
        detail: "Consider location, commute, school district, community amenities, and HOA fees. New construction communities often have well-funded HOAs with great amenities.",
        why: "Your community affects your daily quality of life for years. Choose thoughtfully.",
        how: "Use the Communities tab — I've tagged everything with FHA eligibility, DPA compatibility, and first-time buyer friendliness.",
        agentNote: "Look at HOA fees carefully — a $100/month HOA adds $1,200/year to your housing costs.",
      },
      {
        text: 'Schedule model home tours',
        detail: "Model homes showcase what your home could look like fully upgraded. Identify what's standard vs. upgraded.",
        why: "Seeing the model helps you understand the space and whether it matches your lifestyle.",
        how: "I'll schedule tours and attend every one with you — never go alone to a builder sales office.",
        agentNote: "Ask the sales rep to show you a 'standard' finishes home, not just the model — that's what your base price looks like.",
      },
      {
        text: 'Compare communities on total cost',
        detail: "Price is just the start. Factor in HOA, property taxes (rates vary by city), utilities, and commute costs for a true total cost comparison.",
        why: "A $30K cheaper home in a different city might cost more when all factors are included.",
        how: "I'll build a side-by-side comparison for your top 3 communities.",
        agentNote: "Some cities in the Phoenix metro have dramatically different property tax rates. Goodyear vs. Scottsdale for example.",
      },
    ],
  },
  {
    number: 5,
    name: 'Contract & Design',
    description: 'Sign your purchase agreement and customize your home',
    icon: 'document-text-outline',
    estimatedDays: 30,
    agentTip: "The design center is where your personality meets your home — but budget carefully. Pick 2-3 things you love and keep the rest standard.",
    tasks: [
      {
        text: 'Review purchase agreement',
        detail: "Builder contracts are detailed and builder-favorable. Key items: price escalation protection, cancellation terms, construction timeline guarantees.",
        why: "Understanding what you're signing protects your earnest money and rights.",
        how: "I review every builder purchase agreement with you before signing.",
        agentNote: "As a first-time buyer, you have every right to take 24-48 hours to review the contract before signing.",
      },
      {
        text: 'Design center appointment',
        detail: "You'll select flooring, cabinets, countertops, exterior colors, and upgrades. Bring your vision board, stay hydrated, and take breaks.",
        why: "Design center decisions lock in your home's finishes. Changes after this point are expensive or impossible.",
        how: "I'll prep you with a pre-design center guide including what to upgrade vs. skip.",
        agentNote: "Focus upgrade budget on kitchen countertops, primary bath, and flooring. These have the highest impact and resale value.",
      },
      {
        text: 'Negotiate upgrade allowances and incentives',
        detail: "Builders often offer upgrade credits ($5K-$15K) or closing cost credits instead of price reductions. Use these strategically.",
        why: "Builder incentives are often negotiable, especially on spec homes or at end of quarter.",
        how: "I'll negotiate incentives on your behalf — this is where having an experienced agent pays off significantly.",
        agentNote: "End of the month and end of quarter are the best times to negotiate with builders.",
      },
    ],
  },
  {
    number: 6,
    name: 'Loan Processing',
    description: 'Your lender is working hard — stay responsive',
    icon: 'card-outline',
    estimatedDays: 45,
    agentTip: "The number one thing that slows closings: buyers not responding quickly to lender requests. Check your email and phone daily.",
    tasks: [
      {
        text: 'Respond immediately to lender conditions',
        detail: "Your lender will request additional documents throughout processing — bank statements, letters of explanation, updated pay stubs. Delays in response delay your closing.",
        why: "Builder contracts have closing deadlines. Missing them can cost you your earnest money.",
        how: "Create a dedicated email folder for lender communications. Respond within 24 hours to all requests.",
        agentNote: "I'm copied on all lender communications and will follow up if I see delays on either side.",
      },
      {
        text: "Don't make major financial changes",
        detail: "No new credit cards, no car purchases, no job changes, no large cash deposits. Lenders re-verify your finances right before closing.",
        why: "Any change can trigger a re-review or denial of your loan, even after approval.",
        how: "If you need to make a large purchase or financial change, ask your lender first.",
        agentNote: "I've seen loans denied 5 days before closing because a buyer bought furniture on a new credit card. This is serious.",
      },
      {
        text: 'Lock your interest rate',
        detail: "Rate lock timing is crucial in new construction — builders have long timelines (6-12 months). Ask your lender about extended rate locks and their cost.",
        why: "Rates can rise significantly over a 6-12 month construction period.",
        how: "Discuss rate lock options with your lender at contract signing. Extended locks cost more but provide certainty.",
        agentNote: "Some builders have preferred lenders who offer free extended rate locks as an incentive — compare these carefully.",
      },
    ],
  },
  {
    number: 7,
    name: 'Pre-Closing',
    description: 'Final preparations before closing day',
    icon: 'checkmark-circle-outline',
    estimatedDays: 14,
    agentTip: "Your final walkthrough is your last chance to ensure everything is right. Don't rush it.",
    tasks: [
      {
        text: 'Final walkthrough',
        detail: "Walk every room, test every switch and outlet, run every faucet, check every door and window. Create a blue tape list of anything not finished or damaged.",
        why: "Everything on your list is the builder's responsibility to fix before or after closing per your contract.",
        how: "Schedule at least 2-3 hours for this. I'll do it with you and know what to look for.",
        agentNote: "Bring a phone charger to test outlets. Bring a flashlight. Check under every sink for leaks.",
      },
      {
        text: 'Set up homeowner\'s insurance',
        detail: "You need a policy bound (active) by closing day. New construction often qualifies for discounted rates due to new materials and systems.",
        why: "No insurance = no closing. Your lender requires proof of insurance.",
        how: "Get quotes from at least 3 carriers. Ask about new construction discounts.",
        agentNote: "Your HOA likely has a master policy for common areas — your individual policy covers the inside of your home and personal property.",
      },
      {
        text: 'Set up utilities and services',
        detail: "Arrange for electricity, gas, water (if separately metered), internet, and trash to transfer to your name on closing day.",
        why: "You want lights, water, and internet on day one.",
        how: "Contact utility providers 2 weeks before closing to schedule service start dates.",
        agentNote: "APS, SRP, and SoCalGas (Tucson area) need advance notice. Don't wait until the last minute.",
      },
    ],
  },
  {
    number: 8,
    name: 'Close & Celebrate',
    description: "You did it — welcome home! 🎉",
    icon: 'key-outline',
    estimatedDays: 1,
    agentTip: "This is the moment you've been working toward. Enjoy every second of it.",
    tasks: [
      {
        text: 'Attend closing',
        detail: "Bring your government-issued ID. The closing agent will walk you through each document. You'll sign 50+ pages but the most important are the note (loan) and deed.",
        why: "Your signature makes it official. You're buying a home.",
        how: "Plan 60-90 minutes. Ask questions about anything you don't understand.",
        agentNote: "I'll be at the closing table with you. This is one of my favorite days in real estate.",
      },
      {
        text: 'Receive keys and garage remotes',
        detail: "After recording confirmation, you'll receive all keys, garage remotes, and HOA access cards. Keep them all in one place.",
        why: "You are now a homeowner.",
        how: "Celebrate! Take photos. Make it memorable.",
        agentNote: "Change locks and reprogram garage codes the same day. Builder staff have had access to your home during construction.",
      },
      {
        text: 'Register warranty',
        detail: "New construction comes with a 1-year workmanship warranty, 2-year systems warranty, and 10-year structural warranty (varies by builder). Register it immediately.",
        why: "Warranty registration protects your rights to repairs. Some require registration within 30 days.",
        how: "Register online through the builder's homeowner portal. Keep all documentation.",
        agentNote: "I'll send you a post-closing guide with all the warranty contacts and registration links for your builder.",
      },
    ],
  },
];

export const RELOCATION_JOURNEY: JourneyStageDefinition[] = [
  {
    number: 1,
    name: 'Market Orientation',
    description: 'Learn the Arizona new construction landscape before you commit',
    icon: 'map-outline',
    estimatedDays: 14,
    agentTip: "Phoenix and Tucson are two very different markets. Let me help you understand both before you decide where to focus.",
    tasks: [
      {
        text: 'Phoenix vs. Tucson comparison',
        detail: "Phoenix Metro: Larger market, more communities, higher prices, faster appreciation. Tucson: Smaller, more affordable, military presence, University of Arizona, proximity to Mexico border.",
        why: "Choosing the right metro is the most important first decision for a relocation buyer.",
        how: "I'll build you a custom comparison based on your job location, lifestyle priorities, and budget.",
        agentNote: "Most out-of-state buyers come to Phoenix. Tucson is dramatically underrated and worth serious consideration if your job or base is there.",
      },
      {
        text: 'Learn key neighborhoods and suburbs',
        detail: "Phoenix West Valley: Surprise, Goodyear, Buckeye, Litchfield Park — family-friendly, affordable, near Luke AFB. East Valley: Queen Creek, Gilbert — newer communities, growing. Tucson: Marana, Sahuarita, Vail — master-planned communities.",
        why: "Arizona's metros are sprawling — understanding sub-markets prevents a costly mistake.",
        how: "I'll do a virtual neighborhood tour via video call for any areas you're considering.",
        agentNote: "I've lived and worked in these markets for years. I know which neighborhoods are up-and-coming vs. peaked.",
      },
      {
        text: 'Research commute and lifestyle',
        detail: "Arizona traffic is manageable but freeway-dependent. A 20-mile commute can be 25 minutes or 60 minutes depending on routes and times.",
        why: "Your commute is a daily quality-of-life factor that affects everything.",
        how: "I'll map commute times from your shortlisted communities to your office during peak hours.",
        agentNote: "Phoenix metro sprawl means most people drive 20-40 minutes each way. Plan accordingly.",
      },
    ],
  },
  {
    number: 2,
    name: 'Remote Research',
    description: 'Do your homework from wherever you are now',
    icon: 'laptop-outline',
    estimatedDays: 21,
    agentTip: "I can do a lot of virtual legwork for you before your visit. Let's narrow to 5 communities so your trip is efficient.",
    tasks: [
      {
        text: 'Virtual community tours',
        detail: "Most builders offer virtual tours, video walkthroughs, and interactive floor plan tools online. I can also do a live video walkthrough from the model home.",
        why: "Narrowing your list before flying in saves you time and travel costs.",
        how: "I'll do a live video tour of your top 3 communities on your schedule.",
        agentNote: "I do remote buyer orientations regularly — you don't need to be here to make a highly informed decision.",
      },
      {
        text: 'Research schools and services',
        detail: "Check school districts (GreatSchools.org), proximity to healthcare (important for families and seniors), grocery stores, restaurants, and entertainment.",
        why: "Your neighborhood ecosystem matters for quality of life and resale value.",
        how: "I'll build a community comparison with school ratings and service proximity.",
        agentNote: "Arizona has some excellent charter school options — these are separate from district schools and worth researching.",
      },
      {
        text: 'Review builder track records',
        detail: "Research builder quality ratings, warranty responsiveness, and local reputation. National builders can vary significantly by local division.",
        why: "A great builder national brand doesn't always mean great quality in a specific market.",
        how: "I'll share my direct experience with each builder's Arizona division and connect you with past clients.",
        agentNote: "I've worked with every major builder in the Arizona market. I know which ones are excellent and which to approach carefully.",
      },
    ],
  },
  {
    number: 3,
    name: 'Visit Planning',
    description: 'Maximize your in-person trip to Arizona',
    icon: 'airplane-outline',
    estimatedDays: 7,
    agentTip: "Plan a 3-day trip minimum. Day 1: Orient yourself. Day 2: Tour top communities. Day 3: Decision and possibly writing an offer.",
    tasks: [
      {
        text: 'Schedule model home tours',
        detail: "I'll schedule your tours in geographic order to minimize driving. We'll hit 5-8 communities in 2 days.",
        why: "Seeing homes in person reveals things photos and videos miss — neighborhood feel, traffic, noise, build quality.",
        how: "Share your available dates and I'll build your tour itinerary.",
        agentNote: "Register me as your agent at every new community visit — this protects your right to representation.",
      },
      {
        text: 'Prepare questions for sales reps',
        detail: "Sales reps represent the builder. They're helpful but their job is to sell you their product. Come prepared with the right questions.",
        why: "The right questions reveal a community's true value — and its limitations.",
        how: "I'll give you my 15-question list for builder sales reps before your visit.",
        agentNote: "The questions most people forget: HOA financial health, builder's backlog, lot availability, and pricing trajectory.",
      },
      {
        text: 'Plan your decision timeline',
        detail: "Relocation buyers often need to make faster decisions than local buyers. Know your deadline and work backward.",
        why: "Good lots in popular communities sell fast. Having a decision timeline prevents analysis paralysis.",
        how: "If you're ready to decide during your visit, I'll have the paperwork ready to move quickly.",
        agentNote: "I've helped relocation buyers go from first visit to signed contract in the same day. It's not rushed — it's decisive.",
      },
    ],
  },
  {
    number: 4,
    name: 'Financial Setup',
    description: 'Set up your financing for a remote purchase',
    icon: 'cash-outline',
    estimatedDays: 14,
    agentTip: "Relocation buyers often have equity from their current home. Let's figure out how to leverage it.",
    tasks: [
      {
        text: 'Evaluate out-of-state vs. local lender',
        detail: "Your current lender may be able to do your Arizona purchase, but local lenders often have better knowledge of Arizona programs and builder relationships.",
        why: "Builder preferred lenders sometimes offer special incentives not available to outside lenders.",
        how: "I'll connect you with 2-3 Arizona-based lenders who specialize in new construction and relocation buyers.",
        agentNote: "If you're selling your current home simultaneously, a lender familiar with bridge loans and contingent purchases is valuable.",
      },
      {
        text: 'Plan for gap housing',
        detail: "If your new home closes before your current home sells (or vice versa), plan for temporary housing. Arizona has corporate housing and short-term rentals.",
        why: "Being homeless between transactions is stressful and costly without a plan.",
        how: "I'll outline your gap housing options based on your build timeline and current home situation.",
        agentNote: "New construction build times are 6-12 months — this is actually helpful for planning a coordinated move.",
      },
      {
        text: 'Review relocation assistance from employer',
        detail: "Many employers provide relocation assistance — moving costs, temporary housing, closing cost credits. Don't leave this money on the table.",
        why: "Employer relocation benefits can add $5,000-$50,000+ to your moving budget.",
        how: "Check with your HR department before closing any purchase. Some have specific requirements.",
        agentNote: "If your employer is paying relocation, they may have required lenders or processes. Know these before starting.",
      },
    ],
  },
  {
    number: 5,
    name: 'Remote Contract',
    description: 'Sign your purchase agreement from anywhere',
    icon: 'document-text-outline',
    estimatedDays: 7,
    agentTip: "Builder contracts are fully executable via DocuSign. You don't need to be in Arizona to lock in your home.",
    tasks: [
      {
        text: 'Review purchase agreement remotely',
        detail: "Builder purchase agreements are sent via DocuSign. Review every page — especially contingency clauses, price escalation protection, and construction timeline.",
        why: "You're committing earnest money from 1,000+ miles away. Understand exactly what you're signing.",
        how: "I'll do a video call contract review with you before you execute. Plan 60-90 minutes.",
        agentNote: "I've done hundreds of remote contract reviews. I know exactly what to flag for out-of-state buyers.",
      },
      {
        text: 'Wire earnest money securely',
        detail: "Earnest money for new construction is typically $5,000-$20,000 wired to the title company. Verify wire instructions by calling the title company directly.",
        why: "Wire fraud targets relocation buyers specifically because they're less familiar with local companies.",
        how: "Call the title company at a number you found independently — not from the email. Confirm account details verbally.",
        agentNote: "Never wire based on emailed instructions alone. Always call to verify. I'll help walk you through this.",
      },
    ],
  },
  {
    number: 6,
    name: 'Build Phase',
    description: "Your home is being built — stay connected from afar",
    icon: 'construct-outline',
    estimatedDays: 180,
    agentTip: "I'm your eyes and ears on the ground during construction. I'll visit regularly and send you updates.",
    tasks: [
      {
        text: 'Establish builder portal access',
        detail: "Most builders have an online customer portal with construction photos, milestone updates, and contact forms. Get access immediately after signing.",
        why: "Staying informed remotely prevents surprises at closing.",
        how: "The sales rep will send you login credentials within the first week after signing.",
        agentNote: "I'll also do periodic visits and send you my own updates and photos.",
      },
      {
        text: 'Plan your pre-drywall visit',
        detail: "Fly in for your pre-drywall inspection — this is the most important construction milestone visit for catching issues.",
        why: "Issues found pre-drywall are easy to fix. Post-drywall issues require tearing out walls.",
        how: "Coordinate with your builder for your frame/pre-drywall stage date, then book travel 2-3 weeks out.",
        agentNote: "I'll also do my own pre-drywall inspection and send you detailed photos before your visit.",
      },
      {
        text: 'Plan your final walkthrough trip',
        detail: "Fly in 1-2 days before closing for your final walkthrough and to handle any last-minute details in person.",
        why: "The final walkthrough catches issues that need to be on the builder's warranty list.",
        how: "Book travel for 2-3 days before your scheduled closing date. Build in a buffer for closing delays.",
        agentNote: "I'll coordinate your walkthrough, closing appointment, and any immediate post-closing needs.",
      },
    ],
  },
  {
    number: 7,
    name: 'Pre-Move Prep',
    description: "Get Arizona ready before the moving truck arrives",
    icon: 'cube-outline',
    estimatedDays: 30,
    agentTip: "Arizona summers are brutal for moving. If you have flexibility, target October-April for your move.",
    tasks: [
      {
        text: 'Set up Arizona utilities',
        detail: "APS or SRP for electricity (Phoenix), Tucson Electric Power (Tucson), SoCalGas (Tucson area), and city water. Some communities have specific providers.",
        why: "You need utilities active on closing day.",
        how: "Contact providers 3-4 weeks before closing. Your HOA welcome packet will list the required providers.",
        agentNote: "I'll send you a utility setup guide specific to your community.",
      },
      {
        text: 'Book moving company',
        detail: "Long-distance moves from out-of-state require a licensed interstate mover (FMCSA regulated). Book 4-8 weeks in advance for good availability.",
        why: "Quality movers book up fast, especially in spring/summer.",
        how: "Get 3 binding estimates (not non-binding). Check FMCSA.dot.gov for license verification.",
        agentNote: "Military buyers using DITY/PPM moves have specific weight and reimbursement rules — I can connect you with experienced movers.",
      },
      {
        text: 'Arizona driver license and registration',
        detail: "Arizona law requires a new AZ driver license within 30 days of establishing residency. Vehicle registration within 15 days.",
        why: "Non-compliance can result in fines and affect your legal residency status.",
        how: "Visit MVD Now (AZ MVD online) or an authorized third-party provider. Bring proof of insurance and your current license.",
        agentNote: "AZ has third-party MVD offices (Servicearizona.com authorized offices) that are faster than government MVD offices.",
      },
    ],
  },
  {
    number: 8,
    name: 'Move-In Day',
    description: "Welcome to Arizona — you made it!",
    icon: 'home-outline',
    estimatedDays: 1,
    agentTip: "Pack an essential box for night one: toiletries, phone chargers, a change of clothes, coffee maker, and your favorite snack.",
    tasks: [
      {
        text: 'Complete final walkthrough',
        detail: "If you haven't done a pre-close walkthrough, do it on move-in day before the movers unload. Document any issues.",
        why: "Builder responsibility for issues starts from closing, not after your furniture arrives.",
        how: "Walk every room, test every switch, check every door and window. Document with photos and video.",
        agentNote: "I'll provide you with the builder's warranty contact for any issues that come up in the first year.",
      },
      {
        text: 'Secure your new home',
        detail: "Change all entry locks, reset garage door codes, and set up your security system on day one.",
        why: "Subcontractors and sales staff had access during construction — eliminate that vulnerability immediately.",
        how: "Call a locksmith or use a rekey kit from Home Depot. Garage codes are reset in the owner's manual.",
        agentNote: "Welcome to Arizona! I'll stop by within your first week to see how you're settling in.",
      },
    ],
  },
];

export const SENIOR_JOURNEY: JourneyStageDefinition[] = [
  {
    number: 1,
    name: 'Lifestyle Assessment',
    description: 'Define what your perfect retirement home looks like',
    icon: 'sunny-outline',
    estimatedDays: 14,
    agentTip: "There's no rush. Take time to clearly define what matters most — and what you're finally free from.",
    tasks: [
      {
        text: 'Define must-have lifestyle features',
        detail: "Single-story home? Lock-and-leave convenience? Active social calendar? Resort-style amenities? Quiet neighborhood? Golf? Pickleball? Each 55+ community has a distinct personality.",
        why: "Choosing the right community lifestyle ensures you love where you live for years to come.",
        how: "I'll walk you through a lifestyle questionnaire that maps your priorities to the best-matched communities.",
        agentNote: "The communities I show you will be filtered to exactly your lifestyle priorities — no wasted tours.",
      },
      {
        text: 'Assess accessibility and future needs',
        detail: "Consider single-story, wider doorways (36\"+), no-step entry, walk-in showers, and smart home features. These can often be included or upgraded during new construction.",
        why: "Building in accessibility features during construction is far less expensive than retrofitting later.",
        how: "I'll identify which builders offer aging-in-place packages as standard or at low upgrade cost.",
        agentNote: "Del Webb and Shea specifically design their 55+ homes with these features in mind — often at no extra cost.",
      },
      {
        text: 'Evaluate maintenance preferences',
        detail: "Most 55+ communities include exterior maintenance (landscaping, roof, exterior paint) in HOA fees — true lock-and-leave living.",
        why: "Low-maintenance living is often a key driver for 55+ buyers.",
        how: "I'll compare HOA coverage by community so you know exactly what's included.",
        agentNote: "Even if HOA fees seem high, factor in what you'd spend on yard service, exterior upkeep, and your time — it's often a net savings.",
      },
      {
        text: 'Clarify financial picture',
        detail: "Assess your assets: savings, retirement accounts, proceeds from home sale, Social Security, pension. All can be used for qualifying and down payment.",
        why: "Understanding your full financial picture opens doors to more options.",
        how: "I'll connect you with a lender experienced with retirement income and asset depletion loans.",
        agentNote: "Asset depletion loans count your retirement account balance as income — this is important for buyers with assets but limited income.",
      },
    ],
  },
  {
    number: 2,
    name: 'Community Shortlist',
    description: 'Find your ideal 55+ community in Arizona',
    icon: 'search-outline',
    estimatedDays: 21,
    agentTip: "Arizona has some of the country's best active adult communities. The competition is real — popular communities have wait lists.",
    tasks: [
      {
        text: 'Tour Del Webb communities',
        detail: "Del Webb (owned by PulteGroup) operates Sun City Festival (Buckeye) and other active adult communities in Arizona. Known for resort amenities, social activities, and community design.",
        why: "Del Webb is the gold standard for 55+ living — visiting helps you understand the full lifestyle experience.",
        how: "I'll schedule a Del Webb lifestyle tour which includes a community orientation, model tour, and amenity walkthrough.",
        agentNote: "Del Webb sales events often include exclusive incentives. I'll alert you to these opportunities.",
      },
      {
        text: 'Tour Shea Homes Encanterra',
        detail: "Encanterra in Queen Creek is a resort-style 55+ community with a country club, restaurant, and extensive amenities. Higher price point but exceptional lifestyle.",
        why: "Encanterra represents the premium end of Arizona 55+ living — worth seeing to define your benchmark.",
        how: "Encanterra is invitation-based for community access — I'll schedule your Discovery Experience.",
        agentNote: "Encanterra has a social calendar that rivals any resort. If lifestyle is your priority, this is the benchmark.",
      },
      {
        text: 'Compare total lifestyle cost',
        detail: "Compare HOA fees, included services, clubhouse access, dining options, activity fees, and property taxes for each community.",
        why: "The community with the highest HOA may actually be the best value when all costs are included.",
        how: "I'll build a complete lifestyle cost comparison across your top 3 communities.",
        agentNote: "Look at HOA financials and reserves — underfunded HOAs can result in special assessments.",
      },
      {
        text: 'Check waitlists and availability',
        detail: "Popular 55+ communities in Arizona often have limited new construction inventory and wait lists for specific floor plans.",
        why: "If you find your perfect community, acting quickly prevents losing your preferred lot or plan.",
        how: "I maintain close relationships with 55+ builder sales teams and know current availability.",
        agentNote: "If a community is nearly sold out, I can often find out about upcoming releases before they're publicly advertised.",
      },
    ],
  },
  {
    number: 3,
    name: 'Incentive Stacking',
    description: 'Maximize every savings opportunity available to you',
    icon: 'layers-outline',
    estimatedDays: 7,
    agentTip: "55+ buyers have access to layered incentives that can save $20,000-$40,000+. Let's stack them all.",
    tasks: [
      {
        text: 'Claim design studio credit',
        detail: "Del Webb and Shea Homes offer $10,000-$20,000 design studio credits for 55+ buyers. These cover flooring, counters, appliances, and accessibility upgrades.",
        why: "This is free money toward your home finishes — use every dollar.",
        how: "Design credits are applied at your design center appointment. I'll help you allocate them strategically.",
        agentNote: "Focus design credits on flooring and counters first — they have the highest visual impact and resale value.",
      },
      {
        text: 'Apply for Hometown Heroes credit',
        detail: "Veterans and retired military in 55+ communities can combine the Hometown Heroes credit ($2,000) with other incentives.",
        why: "Every stackable credit reduces your closing costs or purchase price.",
        how: "I'll confirm Hometown Heroes eligibility with your builder at contract.",
        agentNote: "Hometown Heroes at Del Webb + design studio credit can exceed $22,000 in total value for eligible veterans.",
      },
      {
        text: 'Check AZ property tax benefits',
        detail: "Arizona offers property tax deferrals and exemptions for seniors based on income and age. Some counties have additional programs.",
        why: "Reducing ongoing property tax can save thousands per year in retirement.",
        how: "Your county assessor's office handles senior property tax exemptions. Applications are typically due by March 1.",
        agentNote: "100% P&T disabled veterans receive a full property tax exemption in Arizona regardless of age.",
      },
    ],
  },
  {
    number: 4,
    name: 'Contract & Accessibility',
    description: 'Sign your purchase agreement and customize for your needs',
    icon: 'document-text-outline',
    estimatedDays: 30,
    agentTip: "New construction lets you build accessibility in from day one — much cheaper than retrofitting. Don't skip this step.",
    tasks: [
      {
        text: 'Confirm accessibility upgrades in contract',
        detail: "Zero-step entries, wider doorways, roll-in showers, comfort-height toilets, and grab bars should be documented in your purchase agreement or design center selections.",
        why: "Verbal promises from sales reps mean nothing — they must be in the written contract.",
        how: "I'll ensure all accessibility features are listed specifically in your purchase agreement.",
        agentNote: "Many accessibility upgrades are offered at no additional cost by 55+ builders — ask for them all.",
      },
      {
        text: 'Review HOA and community rules',
        detail: "55+ communities have CC&Rs, bylaws, and rules that govern daily life — guest policies, pet rules, rental restrictions, exterior modification rules.",
        why: "You'll live under these rules for years. Understanding them before signing prevents surprises.",
        how: "I'll review the key HOA documents with you and flag anything unusual.",
        agentNote: "Some 55+ communities have strict guest age requirements — important if you have grandchildren who visit frequently.",
      },
      {
        text: 'Smart home tech pre-wire',
        detail: "Pre-wire for security systems, smart lighting, smart thermostats, and in-home medical monitoring. These are cheap to install during construction.",
        why: "Technology for aging-in-place is easier and far less expensive when pre-wired.",
        how: "Ask your builder what smart home pre-wire packages are available.",
        agentNote: "Structured wiring, security pre-wire, and CAT6 ethernet throughout the home cost $500-1,500 during construction vs. $5,000+ to retrofit.",
      },
    ],
  },
  {
    number: 5,
    name: 'Build Phase',
    description: 'Your retirement home is being built',
    icon: 'construct-outline',
    estimatedDays: 180,
    agentTip: "This is an exciting time — enjoy watching your home take shape without stress. That's what I'm here for.",
    tasks: [
      {
        text: 'Monitor construction milestones',
        detail: "Stay connected through the builder portal and my updates. Key milestones: foundation, framing, rough-ins, insulation, drywall, cabinets, flooring.",
        why: "Knowing your construction timeline helps you plan your current home sale and move.",
        how: "I'll send you updates at each major milestone with photos and what to expect next.",
        agentNote: "Coordinate your current home sale timeline with your build timeline — I can help manage both.",
      },
      {
        text: 'Pre-drywall inspection',
        detail: "Have an independent inspector check framing, plumbing, electrical, and HVAC rough-ins before drywall covers everything.",
        why: "This is your opportunity to catch issues while they're inexpensive to fix.",
        how: "I'll schedule an inspector I trust for this stage — plan about 2-3 hours.",
        agentNote: "I'll attend the pre-drywall inspection with you and know exactly what questions to ask.",
      },
    ],
  },
  {
    number: 6,
    name: 'Closing',
    description: 'Simplified closing — we handle the complexity',
    icon: 'checkmark-circle-outline',
    estimatedDays: 14,
    agentTip: "Closing day should feel like a celebration, not a marathon. I'll make sure everything is ready before you arrive.",
    tasks: [
      {
        text: 'Final walkthrough',
        detail: "Walk every room with a detailed checklist. Test everything. Create your blue tape list for builder completion.",
        why: "Items on the blue tape list are the builder's responsibility — don't skip this step.",
        how: "I'll do the walkthrough with you and coach you on what to look for.",
        agentNote: "Take your time. There's no rush. This is one of your biggest purchases ever.",
      },
      {
        text: 'Review closing documents in advance',
        detail: "Request your closing documents 48 hours before closing. Review at home, calmly — not under time pressure at the signing table.",
        why: "Having time to review prevents last-minute confusion or pressure at the closing table.",
        how: "Ask your title company to send the closing package electronically 2 days before closing.",
        agentNote: "If anything in the documents looks different from what you expected, call me immediately — don't sign until we've reviewed it.",
      },
      {
        text: 'Celebrate!',
        detail: "You've earned this. Closing day is a milestone to be celebrated.",
        why: "This is one of the best days you'll have — mark it properly.",
        how: "Plan a small celebration — I'll be there with you!",
        agentNote: "I always bring something to make closing day special. It's one of my favorite parts of this job.",
      },
    ],
  },
  {
    number: 7,
    name: 'Welcome Home',
    description: "Your next great chapter begins now",
    icon: 'heart-outline',
    estimatedDays: 7,
    agentTip: "The first 30 days are about getting settled and meeting your new neighbors. The community events calendar is your best friend.",
    tasks: [
      {
        text: 'Register builder warranty',
        detail: "New construction warranties cover workmanship (1 year), systems (2 years), and structure (10 years). Register immediately.",
        why: "Warranty registration protects your rights to repairs.",
        how: "Register online through your builder's homeowner portal within 30 days of closing.",
        agentNote: "I'll send you all the warranty and homeowner resource links for your specific builder.",
      },
      {
        text: 'Set up community amenities access',
        detail: "Get your community access cards, pool keys, gym fobs, and club memberships set up with your HOA.",
        why: "The amenities are why you chose this community — start using them from day one.",
        how: "Your HOA welcome packet has all the setup instructions. Visit the HOA office in the first week.",
        agentNote: "Join the community Facebook or Nextdoor group immediately — it's how you'll hear about events and connect with neighbors.",
      },
      {
        text: 'Explore community events',
        detail: "Most 55+ communities have a packed social calendar — clubs, classes, events, and trips. Getting involved quickly sets the tone for your community experience.",
        why: "Social connection is one of the biggest factors in retirement happiness.",
        how: "Get the community events calendar from the HOA and commit to attending one event in your first week.",
        agentNote: "The people in these communities are incredible. You'll find your tribe quickly.",
      },
    ],
  },
];

export const JOURNEY_BY_BUYER_TYPE: Record<string, JourneyStageDefinition[]> = {
  veteran: VETERAN_JOURNEY,
  first_time: FIRST_TIME_JOURNEY,
  relocation: RELOCATION_JOURNEY,
  senior: SENIOR_JOURNEY,
};
